### ISSUE TITLE
Add integration with Kafka

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/spring-boot-open-telemetry-demo#72]
On hit GET endpoint send small message to Kafka (LocalDateTime.now() will be OK).  
Add tests to cover context propagation to Kafka (read message from Kafka in test and ensure that `traceparent `header presents).   
Add Kafka broker to docker-compose file for local development.  
Use SASL_PLAINTEXT for auth to Kafka (with username and password).

**Comment by botelhorui** [comment]
Hi,

I'm new to open source contributing and I'm interested in working on this issue. Is it still open for contributions?

Thanks,

**Comment by mfvanek** [comment]
Hi @botelhorui,
yes it's still open. Feel free to contribute.
I've updated description and added some points

**Comment by mfvanek** [comment]
Hi @botelhorui 
Any updates on this?

**Comment by botelhorui** [comment]
> Hi @botelhorui 
> Any updates on this?

Hi @mfvanek 
Could you please reassign this task? Due to lack of time.
